version: "3.8"
services:
  api:
    build: ./backend
    environment:
      - NASA_API_KEY=${NASA_API_KEY}
      - CLIENT_ORIGIN=${CLIENT_ORIGIN}
    expose:
      - "4000"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/certs:ro   # SSL certs go here
    depends_on:
      - api
