version: "3.8"
services:
  api:
    build: ./backend
    environment:
      - NASA_API_KEY=${NASA_API_KEY}
      - CLIENT_ORIGIN=${CLIENT_ORIGIN}
    expose:
      - "4000"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - api
    restart: unless-stopped
