# .github/workflows/deploy.yml
name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}         # set in Settings → Secrets → Actions
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}      # your PEM, set as an Actions secret
          script: |
            cd ~/astronomy-view
            git pull origin main
            docker-compose down
            docker-compose up -d --build

      - name: Confirm services are up
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker-compose ps

